#改成需要的关键词
keyword: 
  #24.7
  - 魔导具师妲莉亚永不妥协～从今天开始的自由职人生活～
  - 女神的露天咖啡厅
  - 德里科的托儿所
  - 物语系列
  - 妖精的尾巴 百年任务
  - 你与我最后的战场，亦或是世界起始的圣战
  - 恋语轻唱
  
  #24.10
  - 孤单一人的异世界攻略
  - 重来吧，魔王大人
  - 话术士
  - 叹气的亡灵想隐退
  - 结缘甘神神社
  - 成为名垂青史的反派大小姐吧
  - Re：从零开始的异世界生活
  - Acro Trip
  - 悲喜渔生
  - 青之箱
  - 真的要结婚吗
  - 机械手臂
  - 胆大党
  - 再见龙生，你好人生
  - 柔光魔女股份有限公司
  - 刀剑神域外传 暴风之铳
  - 在地下城寻求邂逅是否搞错了什么
  - 偶像大师 闪耀色彩
  - 到了联谊会上发现连一个女生都没有
  - 没能成为魔法师的女孩子的故事
  - 冻牌~地下麻将斗牌录~
  - 死神
  - 关于地球的运动
  - 青之驱魔师
  - 暗杀女仆冥土小姐
  - 被队伍驱逐的治愈师，其实是最强的
  - 魔王2099
  - LoveLive! Superstar!!
  - 妻子变成小学生。
  - 可爱史莱姆噗尼露
  - 香格里拉边境
  - 乱马
  - 村井之恋
  - Duel Masters LOST ～追憶の水晶～
  - 机动战士高达 复仇的安魂曲
  - 重生大小姐正在攻略龙帝殿下
  - Murder Mystery of the Dead
  - 妖怪学校的
  - 辰星降临之国的妮娜
  - 精灵幻想记
  - 平凡职业造就世界最强


#Jellyfin中Webhook Url地址
receive_url: 'http://localhost:11451'

#转发的地址
forward_url: 'http://localhost:11721/send_group_msg'
