keyword: 
  #25.7
  - 章鱼哔的原罪
  - 禁止入內的鼹鼠
  - 美食广场
  - 碧蓝之海
  - 绝对不行
  - 宇宙恐怖秀
  - 最近的侦探真没用
  - 阿松
  - 保龄球少女！
  - 魔兽之王与婴儿与尸之勇者
  - 转生成自动贩卖机
  - 地狱老师
  - 阴阳回天
  - 强者的新传说
  - 盾之勇者成名录
  - 七王子
  - 吊带袜天使
  - 流放者食堂
  - 神椿市建设中
  - 胆大党
  - 水属性魔法使
  - 双人单身露营
  - 去唱卡拉OK吧
  - 石纪元
  - 彻夜之歌
  - 明日方舟
  - 沉默魔女的秘密
  - 渡君的XX即将崩坏
  - 租借女友
  - 桃源暗鬼
  - 拔作岛
  - 支配者的王冠
  - 气绝勇者与暗杀公主
  - 费马的料理
  - 青春猪头少年
  - 更衣人偶坠入爱河
  - 坏女孩
  - 白魔导师
  - 薰香花朵凛然绽放
  - 光死去的夏天
  - 和雨和你
  - 公爵千金的家庭教师
  - 噗妮露是可爱史莱姆
  - 琉璃的宝石
  - 异世界默示录
  - 活死喵之夜
  - 废渊战鬼
  - 与游戏中心的少女异文化交流的故事
  - 肥宅勇者
  - 杀手旅店
  - 小城日常
  - 利维坦号战记
  - BULLET/BULLET
  - 帝乃三姐妹意外地容易相处
  - 异形

  #25.10
  - 永久的黄昏

  
#Jellyfin中Webhook Url地址
receive_url: 'http://localhost:11451'

#转发的地址
forward_url: 'http://127.0.0.1:11721/send_group_msg'
