#改成需要的关键词
keyword: 
  #24.7
  - 妖精的尾巴 百年任务
  - 你与我最后的战场，亦或是世界起始的圣战
  - 恋语轻唱
  
  #24.10
  - 死神
  - 关于地球的运动
  - 香格里拉边境
  - Duel Masters
  - 谋杀之谜：亡者的秘密
  - 龙珠大魔

  #25.1
  - 贝希摩斯
  - 命运
  - 上班族
  - 魔法使的约定
  - 这公司有我喜欢的人
  - 我的可爱对黑岩目高不管用
  - 注定没落的贵族
  - 缘结甘神家
  - 果实大师
  - 无名记忆
  - 群花绽放
  - 终将成为最强炼金术师
  - 天久鹰央的推理病历表
  - 灰色：幻影扳机
  - 黄昏旅店
  - 异修罗
  - 异世界魔法
  - 蜂蜜柠檬苏打
  - 从零开始的异世界生活
  - 青之箱
  - 在地下城寻求邂逅是否搞错了什么
  - 颂乐人偶
  - MOMENTARY LILY
  - 中年男的异世界网购生活
  - 鉴定士
  - 中年大叔转生反派千金
  - 想星
  - 冻牌
  - 和班上最讨厌的女生结婚了
  - 一杆青空
  - 欢迎来到日本
  - 魔农传记
  - 药屋少女的呢喃
  - 柜台小姐
  - 魔域英雄传说
  - 青之驱魔师
  - 我独自升级
  - 女忍者
  - 冲绳
  - 金牌得主
  - 坂本日常
  - ババンババンバンバンパイア
  - 吸血鬼
  - A级队伍
  - 全修
  - 超超超超超喜欢你的100个女朋友
  - 光之美少女
  - 红战士

  #25.4
  - 阿波连
  - 随兴旅
  - 夏日口袋
  - 战斗天赋解析系统
  - 魔女消逝
  - 阳光马达棒球场
  - 紫云寺家的孩子们
  - GQuuuuuuX
  - 末日后酒店
  - 拜托请穿上，鹰峰同学
  - 记忆缝线
  - 圣女因太过完美不够可爱而被废除婚约并卖到邻国
  - 最强王者，第二人生要做什么？
  - 外星人姆姆
  - 天才治疗师退队作为无照治疗师快乐过活
  - 摇滚乃是淑女的爱好
  - 你与我最后的战场，亦或是世界起始的圣战
  - 忍者与杀手二人组的日常生活
  - 男女之间存在纯友情吗？（不，不存在！！）
  - 再见，地球
  - 炎炎消防队
  - 推理要在晚餐后
  - 真･武士传 剑勇传说
  - 打了300年的史莱姆，不知不觉就练到了满级
  - 罪恶装备 奋战：两位裁决者
  - 乡下大叔成为剑圣
  - 小市民系列
  - 我是星际国家的恶德领主！
  - mono女孩
  - 时光流逝，饭菜依旧美味
  - 使人误解的工房主～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～
  - 赛马娘 芦毛灰姑娘
  - 魔女与使魔
  - 前桥魔女
  - 受到猩猩之神庇护的大小姐在皇家骑士团受到宠爱
  - 拉撒路
  - 爱有点沉重的暗黑精灵从异世界紧追不放
  - 快藏起来！玛琪娜同学！！
  - 月出之战
  - 莉可丽丝
  - 九龙大众浪漫
  - 为美好的世界献上祝福！
  - MyGO!!!!!
  - U探泰拉

  #25.7
  - 章鱼哔的原罪
  - 禁止入內的鼹鼠
  - 美食广场
  - 碧蓝之海
  - 绝对不行
  - 宇宙恐怖秀
  - 最近的侦探真没用
  - 阿松
  - 保龄球少女！
  - 魔兽之王与婴儿与尸之勇者
  - 转生成自动贩卖机
  - 地狱老师
  - 阴阳回天
  - 强者的新传说
  - 盾之勇者成名录
  - 七王子
  - 吊带袜天使
  - 流放者食堂
  - 神椿市建设中
  - 胆大党
  - 水属性魔法使
  - 双人单身露营
  - 去唱卡拉OK吧
  - 石纪元
  - 彻夜之歌
  - 明日方舟
  - 沉默魔女的秘密
  - 渡君的XX即将崩坏
  - 租借女友
  - 桃源暗鬼
  - 拔作岛
  - 支配者的王冠
  - 气绝勇者与暗杀公主
  - 费马的料理
  - 青春猪头少年
  - 更衣人偶坠入爱河
  - 坏女孩
  - 白魔导师
  - 薰香花朵凛然绽放
  - 光死去的夏天
  - 和雨和你
  - 公爵千金的家庭教师
  - 噗妮露是可爱史莱姆
  - 琉璃的宝石
  - 异世界默示录
  - 活死喵之夜
  - 废渊战鬼
  - 与游戏中心的少女异文化交流的故事
  - 肥宅勇者
  - 杀手旅店
  - 小城日常
  - 利维坦号战记
  - BULLET/BULLET
  - 帝乃三姐妹意外地容易相处
  - 异形

  #25.10
  - 永久的黄昏

  
#Jellyfin中Webhook Url地址
receive_url: 'http://localhost:11451'

#转发的地址
forward_url: 'http://127.0.0.1:11721/send_group_msg'
