#改成需要的关键词
keyword: 
  - 夜晚游玩生活 
  - 再见，地球
  - 杖与剑的魔剑谭
  - 身为VTuber的我因为忘记关台而成了传说
  - 夜樱家的大作战
  - 这个世界漏洞百出
  - 魔导具师妲莉亚永不妥协～从今天开始的自由职人生活～
  - 败犬女主太多了！
  - 小市民系列
  - 亚托莉 -我挚爱的时光-
  - 擅长逃跑的殿下
  - 地下城里的人们
  - 天穗之咲稻姬
  - 为何我的世界被遗忘了？
  - 关于我转生变成史莱姆这档事
  - DDDD 恶魔的破坏
  - 女神的露天咖啡厅
  - 2.5次元的诱惑
  - 恋爱无法用双子除尽
  - 德里科的托儿所
  - 义妹生活
  - 靠废柴技能【状态异常】成为最强的我将蹂躏一切
  - 疑似后宫
  - 我要【招架】一切~反误解的世界最强想成为冒险者～
  - 异世界失格
  - 异世界自杀小队
  - 亦叶亦花
  - 鹿乃子乃子虎视眈眈
  - 不时用俄语小声说真心话的邻桌艾莉同学
  - 【我推的孩子】
  - 魔王军最强的魔术师是人类
  - 魔法少女与邪恶曾经敌对。
  - 深夜重拳
  - 从路人角色开始的探索英雄谭
  - 物语系列
  - 异世界悠闲纪行～边养娃边当冒险者～
  - 妖精的尾巴 百年任务
  - 尼尔：自动人形
  - 前辈是男孩子
  - 你与我最后的战场，亦或是世界起始的圣战
  - 狼与香辛料 行商邂逅贤狼
  - Code Geass 夺还的罗赛
  - 大叔新人冒险者，被最强小队拼死锻炼后无敌了
  - 恋语轻唱
  
  #24.10
  - 孤单一人的异世界攻略
  - 重来吧，魔王大人
  - 最狂辅助职业【话术士】世界最强战团听我号令
  - 叹气的亡灵想隐退
  - 结缘甘神神社
  - 成为名垂青史的反派大小姐吧

#Jellyfin中Webhook Url地址
receive_url: 'http://localhost:11451'

#转发的地址
forward_url: 'http://localhost:11721/send_group_msg'
